export const projects = [
  {
    title: "Envoy Load Balancer",
    category: "Networking",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/envoy-load-balancer",
  },
  {
    title: "Local Git Contributions Stats",
    category: "Command-Line Tools",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/cli-tool-go-git-local-stats",
  },
  {
    title: "wget Clone",
    category: "Command-Line Tools",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/cli-tool-wget-clone",
  },
  {
    title: "Joint Bank Account",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/joint-bank-account-smart-contract",
  },
  {
    title: "NFT Auction",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/nft-auction",
  },
  {
    title: "ERC721 - Token (NFTs)",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/erc721-token",
  },
  {
    title: "ERC20 - Token",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/erc20-token",
  },
  {
    title: "Decentralized Voting",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/decentralized-voting",
  },
  {
    title: "Quora Question Pair Similarity",
    category: "Data Science/Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/qqp-similarity",
  },
  {
    title: "Check-In App",
    category: "Full Stack Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/check-in-app",
  },
  {
    title: "Google Store Revenue Prediction",
    category: "Data Science/Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/gstore-revenue-prediction",
  },
];

export const skills = [
  {
    icon: "",
    category: "Programming Languages",
    names: [
      "Javscript,",
      "Python,",
      "Go,",
      "Java,",
      "Kotlin,",
      "PHP,",
      "C#,",
      "C and C++,",
      "TypeScript,",
      "SQL,",
      "HTML,",
      "CSS,",
      "Perl,",
      "NoSQL,",
      "Rust",
    ],
  },
  {
    icon: "",
    category: "Cloud Computing",
    names: [
      "Amazon Web Services (AWS),",
      "Microsoft Azure,",
      "Google Cloud Platform,",
      "EnvoyProxy,",
      "gRPC,",
      "Prometheus,",
      "Graphana,",
      "Zipkin,",
      "Apache Druid,",
      "Kafka",
    ],
  },
  {
    icon: "",
    category: "Back-End Frameworks",
    names: [
      "Spring and Spring Boot,",
      "Hibernate,",
      "Django,",
      "Flask,",
      "Mulesoft,",
      "Kong",
    ],
  },
  {
    icon: "",
    category: "Front-End Frameworks",
    names: [
      "ReactJS,",
      "AngularJS,",
      "VueJS,",
      "Web3.js,",
      "Ether.js,",
      "jQuery",
    ],
  },
  {
    icon: "",
    category: "Operating Systems",
    names: ["Linux,", "Unix,", "Mac OS,", "Windows"],
  },
  {
    icon: "",
    category: "DevOps Tools",
    names: [
      "Git,",
      "Docker,",
      "Puppet,",
      "Ansible,",
      "Selenium,",
      "Jenkins,",
      "TeamCity,",
      "Kubernetes,",
      "Splunk",
    ],
  },
  {
    icon: "public/treeLogo.png",
    category: "Databases",
    names: [
      "OracleDB,",
      "Microsoft SQL Server,",
      "MySQL,",
      "PostgreSQL,",
      "DynamoDB,",
      "MariaDB,",
      "Apache Cassandra,",
      "MongoDB",
    ],
  },
  {
    icon: "",
    category: "Blockchain/Web3",
    names: [
      "Solidity,",
      "Ganache,",
      "Truffle,",
      "Hardhat,",
      "Ethereum,",
      "MetaMask,",
      "Alchemy",
    ],
  },
];

export const experiences = [
  {
    company: "TD Securities",
    role: "Software Engineer (API Platform)",
    location: "New York, NY, United States",
    duration: "October 2022 – Present",
    details: ["abc", "def"],
  },
  {
    company: "HSBC",
    role: "Software Engineer (Infrastructure)",
    location: "Jersey City, NJ, United States",
    duration: "November 2019 – October 2022",
    details: ["abc", "def"],
  },
  {
    company: "Field Point Servicing",
    role: "Data Analytics Intern",
    location: "Greenwich, CT, United States",
    duration: " May 2019 – August 2019",
    details: ["abc", "def"],
  },
];
