export const projects = [
  {
    title: "Joint Bank Account",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/joint-bank-account-smart-contract",
  },
  {
    title: "NFT Auction",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/nft-auction",
  },
  {
    title: "ERC721 - Token (NFTs)",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/erc721-token",
  },
  {
    title: "ERC20 - Token",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/erc20-token",
  },
  {
    title: "Decentralized Voting",
    category: "Blockchain/Web3",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/decentralized-voting",
  },
  {
    title: "Quora Question Pair Similarity",
    category: "Data Science/Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/qqp-similarity",
  },
  {
    title: "Check-In App",
    category: "Full Stack Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/check-in-app",
  },
  {
    title: "Google Store Revenue Prediction",
    category: "Data Science/Engineering",
    description: "",
    image: "",
    link: "https://github.com/siddharthkhonde/gstore-revenue-prediction",
  },
];

export const skills = [
  {
    icon: "public/treeLogo.png",
    category: "Programming Languages",
    names: [
      "Java,",
      "C,",
      "C++,",
      "Golang,",
      "SQL,",
      "Python,",
      "Perl,",
      "CSS,",
      "HTML,",
      "JavaScript,",
      "AngularJs,",
      "NodeJs,",
      "ReactJs",
    ],
  },
  {
    icon: "public/treeLogo.png",
    category: "Operating Systems",
    names: ["Linux,", "Unix,", "Mac OS,", "Windows"],
  },
  {
    icon: "public/treeLogo.png",
    category: "DevOps Tools",
    names: [
      "Git",
      "Docker",
      "Puppet",
      "Ansible",
      "Selenium",
      "Jenkins",
      "Kubernetes",
      "Splunk",
    ],
  },
  {
    icon: "public/treeLogo.png",
    category: "Frameworks",
    names: [
      "Spring,",
      "Spring Boot,",
      "Hibernate,",
      "Restful Webservices,",
      "Maven,",
      "Gradle,",
      "Microservices,",
      "MuleSoft,",
      "Kong,",
      "AWS",
    ],
  },
  {
    icon: "public/treeLogo.png",
    category: "Database",
    names: ["OracleDB", "Microsoft SQL Server", "MySQL", "DynamoDB", "MongoDB"],
  },
  {
    icon: "public/treeLogo.png",
    category: "Software",
    names: [
      "Microsoft Office",
      "Adobe Photoshop",
      "MATLAB",
      "IBM SPSS Modeler for Analytics",
      "Tableau",
      "Eclipse",
    ],
  },
  {
    icon: "public/treeLogo.png",
    category: "Project Management Tools",
    names: ["Jira", "Confluence"],
  },
  {
    icon: "%PUBLIC_URL%/os.png",
    category: "Blockchain Technology",
    names: ["Solidity", "Ganache", "Truffle", "Hardhat", "Web3.js", "Ether.js"],
  },
];

export const experiences = [
  {
    company: "TD Securities",
    role: "Software Engineer (API Platform)",
    location: "New York, NY, United States",
    duration: "October 2022 – Present",
    details: ["abc", "def"],
  },
  {
    company: "HSBC",
    role: "Software Engineer (Infrastructure)",
    location: "Jersey City, NJ, United States",
    duration: "November 2019 – October 2022",
    details: ["abc", "def"],
  },
  {
    company: "Field Point Servicing",
    role: "Data Analytics Intern",
    location: "Greenwich, CT, United States",
    duration: " May 2019 – August 2019",
    details: ["abc", "def"],
  },
];
